---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: 'pv-pim-demo'
  labels:
    app: pv-pim-demo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: '10.10.10.26'
    path: '/volume1/export/demo/pim'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'pvc-pim-demo'
spec:
  selector:
    matchLabels:
      app: 'pv-pim-demo'
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 2Gi
